// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(OrderSistemaSupermercadoContext))]
    partial class OrderSistemaSupermercadoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Model.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_COMPRA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_COMPRA")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("ID_PROVEEDOR");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("ID_SUCURSAL");

                    b.Property<int?>("IdTransportista")
                        .HasColumnType("int")
                        .HasColumnName("ID_TRANSPORTISTA");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MONTO_TOTAL");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NUMERO_DOCUMENTO");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_DOCUMENTO");

                    b.HasKey("IdCompra");

                    b.HasIndex(new[] { "NumeroDocumento" }, "UQ__COMPRA__87B6EC7EAF707742")
                        .IsUnique()
                        .HasFilter("[NUMERO_DOCUMENTO] IS NOT NULL");

                    b.ToTable("COMPRA", (string)null);
                });

            modelBuilder.Entity("Domain.Model.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DETALLE_COMPRA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleCompra"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_REGISTRO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int")
                        .HasColumnName("ID_COMPRA");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<decimal?>("PrecioCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("PRECIO_COMPRA");

                    b.Property<decimal?>("PrecioVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("PRECIO_VENTA");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SUBTOTAL");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.ToTable("DETALLE_COMPRA", (string)null);
                });

            modelBuilder.Entity("Domain.Model.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_DETALLE_VENTA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleVenta"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("CANTIDAD");

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DESCUENTO");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_REGISTRO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("ID_PRODUCTO");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("PRECIO_VENTA");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("SUBTOTAL");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdVenta");

                    b.ToTable("DETALLE_VENTA", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Log", b =>
                {
                    b.Property<int>("Id_Log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_LOG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Log"));

                    b.Property<string>("Codigo_Error")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CODIGO_ERROR");

                    b.Property<string>("Detalle_Error")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("DETALLE_ERROR");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ENDPOINT");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Mensaje_Error")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("MENSAJE_ERROR");

                    b.Property<string>("Metodo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("METODO");

                    b.Property<string>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ERROR")
                        .HasColumnName("NIVEL");

                    b.HasKey("Id_Log");

                    b.ToTable("LOG", (string)null);
                });

            modelBuilder.Entity("Domain.Model.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VENTA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<decimal?>("Descuento")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("DESCUENTO");

                    b.Property<DateTime?>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FECHA_VENTA")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("ID_CLIENTE");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("ID_SUCURSAL");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<decimal?>("MontoCambio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MONTO_CAMBIO");

                    b.Property<decimal?>("MontoPago")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MONTO_PAGO");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("MONTO_TOTAL");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NUMERO_DOCUMENTO");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TIPO_DOCUMENTO");

                    b.HasKey("IdVenta");

                    b.HasIndex(new[] { "NumeroDocumento" }, "UQ__VENTA__87B6EC7E76F1FEDA")
                        .IsUnique()
                        .HasFilter("[NUMERO_DOCUMENTO] IS NOT NULL");

                    b.ToTable("VENTA", (string)null);
                });

            modelBuilder.Entity("Domain.Model.DetalleCompra", b =>
                {
                    b.HasOne("Domain.Model.Compra", "IdCompraNavigation")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCompraNavigation");
                });

            modelBuilder.Entity("Domain.Model.DetalleVenta", b =>
                {
                    b.HasOne("Domain.Model.Venta", "IdVentaNavigation")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdVentaNavigation");
                });

            modelBuilder.Entity("Domain.Model.Compra", b =>
                {
                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("Domain.Model.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
